[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "fastapi_msal"
author = "Dudi Levy"
classifiers = [ "License :: OSI Approved :: MIT License",]

